function Data() {
    this.arr = new Array();
}

Data.prototype.array = {
    "six_correct": [
        "jazzed",
        "puzzle",
        "fuzzed",
        "buzzed",
        "zigzag",
        "buzzer",
        "jacked",
        "jumble",
        "hijack",
        "jumped",
        "jackal",
        "joypop",
        "pyjama",
        "assume",
        "author",
        "battle",
        "abroad",
        "acting",
        "afraid",
        "advice",
        "bishop",
        "belong",
        "before",
        "animal",
        "agenda",
        "agency",
        "gather",
        "global",
        "garden",
        "guilty",
        "french",
        "forest",
        "import",
        "injury",
        "impact",
        "island",
        "killed",
        "launch",

    ],

    "six_wrong": [
        "dzazej",
        "lpuzez",
        "fdzezu",
        "bdzuez",
        "gzgaiz",
        "ruzebz",
        "ajkcde",
        "ejbmul",
        "khciaj",
        "ujpmde",
        "lcakaj",
        "poypjo",
        "apmjay",
        "eamsus",
        "rohaut",
        "ebltat",
        "daaorb",
        "agnitc",
        "dairaf",
        "aevidc",
        "bshiop",
        "loebng",
        "brofee",
        "naimal",
        "geaadn",
        "cynega",
        "rgeaht",
        "lgabol",
        "gnedar",
        "ygutil",
        "fchren",
        "tesfor",
        "rtopmi",
        "yrujni",
        "ticmap",
        "dnalsi",
        "dellik",
        "unchla",
    ]
}